#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-freemarker
Version  : 2.3.20
Release  : 1
URL      : https://github.com/apache/freemarker/archive/v2.3.20.tar.gz
Source0  : https://github.com/apache/freemarker/archive/v2.3.20.tar.gz
Source1  : https://repo1.maven.org/maven2/org/freemarker/freemarker/2.3.20/freemarker-2.3.20.jar
Source2  : https://repo1.maven.org/maven2/org/freemarker/freemarker/2.3.20/freemarker-2.3.20.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Entessa
Requires: mvn-freemarker-data = %{version}-%{release}
BuildRequires : apache-ant
BuildRequires : buildreq-mvn

%description
===============================================================================
FreeMarker {version}

%package data
Summary: data components for the mvn-freemarker package.
Group: Data

%description data
data components for the mvn-freemarker package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/freemarker/freemarker/2.3.20
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/freemarker/freemarker/2.3.20/freemarker-2.3.20.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/freemarker/freemarker/2.3.20
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/freemarker/freemarker/2.3.20/freemarker-2.3.20.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/freemarker/freemarker/2.3.20/freemarker-2.3.20.jar
/usr/share/java/.m2/repository/org/freemarker/freemarker/2.3.20/freemarker-2.3.20.pom
